export default [
    {
        id:1,
        title:"用户管理",
        url:"",
        icon:"mdi-account-box-multiple",
        children:[
            {
                id:7,
                title:"BDP用户",
                url:"/pages/bdpUser",
                icon:"mdi-file-document-outline",
                parentId:1
            },
            {
                id:8,
                title:"角色设计",
                url:"/pages/roleDesign",
                icon:"mdi-file-document-outline",
                parentId:1
            },
            {
                id:9,
                title:"角色列表",
                url:"/pages/roleList",
                icon:"mdi-file-document-outline",
                parentId:1
            },
            {
                id:10,
                title:"用户授权",
                url:"/pages/userAuthorize",
                icon:"mdi-file-document-outline",
                parentId:1
            }
        ],
        parentId:0
    },
    {
        id:2,
        title:"数据核销",
        url:"",
        icon:"mdi-chart-box-plus-outline",
        children:[
            {
                id:11,
                title:"异常核销",
                url:"/pages/awsmCc",
                icon:"mdi-file-document-outline",
                parentId:2
            },
            {
                id:12,
                title:"出境核销",
                url:"/pages/overseaCc",
                icon:"mdi-file-document-outline",
                parentId:2
            },
            {
                id:13,
                title:"打印挂签",
                url:"/pages/printA",
                icon:"mdi-file-document-outline",
                parentId:2
            },
            {
                id:14,
                title:"类别判断",
                url:"/pages/typeCharge",
                icon:"mdi-file-document-outline",
                parentId:2
            }
        ],
        parentId:0
    },
    {
        id:3,
        title:"报表统计",
        url:"",
        icon:"mdi-chart-areaspline",
        children:[
            {
                id:15,
                title:"场地数据",
                url:"/pages/transitData",
                icon:"mdi-file-document-outline",
                parentId:3
            },
            {
                id:16,
                title:"航班规划",
                url:"/pages/flightPlan",
                icon:"mdi-file-document-outline",
                parentId:3
            },
            {
                id:17,
                title:"新增流程",
                url:"/pages/newProgress",
                icon:"mdi-file-document-outline",
                parentId:3
            },
            {
                id:18,
                title:"样板监控",
                url:"/pages/watcher",
                icon:"mdi-file-document-outline",
                parentId:3
            }
        ],
        parentId:0
    }
]
